version: '3'

services:
  web:
    image: imotechsl/digicard:${ENV}
    container_name: digicard-web-${ENV}
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - 3000:3000
    stdin_open: true
    volumes:
      - ./:/usr/src/app
      - /usr/src/node_modules



